name: Move Azure Resources

on:
  workflow_dispatch:
    inputs:
      azureSubscription:
        description: 'Azure Subscription ID'
        required: true
      tenantId:
        description: 'Azure Tenant ID'
        required: true
      clientId:
        description: 'Azure Client ID'
        required: true
      clientSecret:
        description: 'Azure Client Secret'
        required: true
      sourceResourceGroupId:
        description: 'Source Resource Group Name'
        required: true
      destinationResourceGroupId:
        description: 'Destination Resource Group Name'
        required: true
      resourceIds:
        description: 'Resource IDs to move (comma-separated)'
        required: true

jobs:
  move-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        run: |
          az login --service-principal \
            --username "${{ github.event.inputs.clientId }}" \
            --password "${{ github.event.inputs.clientSecret }}" \
            --tenant "${{ github.event.inputs.tenantId }}"

      - name: Set Azure Subscription
        run: az account set --subscription ${{ github.event.inputs.azureSubscription }}

      - name: Move Resources
        run: |
          az resource move \
            --destination-group ${{ github.event.inputs.destinationResourceGroupId }} \
            --ids ${{ github.event.inputs.resourceIds }}

      - name: Logout of Azure
        run: az logout
