name: Move Azure Resources
on:
  workflow_dispatch:
    inputs:
      azureSubscription:
        description: 'Azure Subscription ID'
        required: true
      tenantId:
        description: 'Azure Tenant ID'
        required: true
      clientId:
        description: 'Azure Client ID'
        required: true
      clientSecret:
        description: 'Azure Client Secret'
        required: true
      sourceResourceGroupId:
        description: 'Source Resource Group ID'
        required: true
      destinationResourceGroupId:
        description: 'Destination Resource Group ID'
        required: true
      resourceIds:
        description: 'Resource IDs to move (comma-separated)'
        required: true

jobs:
  move-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Azure CLI
        uses: azure/setup-azure@v1
        with:
          azureSubscription: ${{ github.event.inputs.azureSubscription }}
          tenantId: ${{ github.event.inputs.tenantId }}
          clientId: ${{ github.event.inputs.clientId }}
          clientSecret: ${{ github.event.inputs.clientSecret }}

      - name: Move Resources
        run: |
          az resource move \
            --resource-group-id ${{ github.event.inputs.sourceResourceGroupId }} \
            --destination-resource-group ${{ github.event.inputs.destinationResourceGroupId }} \
            --resource-ids ${{ github.event.inputs.resourceIds }}
