name: Move Azure Resources

on:
  push:
    branches:
      - main  # Change as per your requirement

jobs:
  move-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: Azure/setup-azure@v1
        with:
          azure-clients-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-clients-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Move Azure resources
        run: |
          # Define your parameters
          RESOURCE_GROUP_NAME="source-resource-group"
          TARGET_RESOURCE_GROUP_NAME="target-resource-group"
          RESOURCES="resource1 resource2" # Add the resources you want to move

          # Move the resources
          az resource move --destination-group $TARGET_RESOURCE_GROUP_NAME --ids $RESOURCES
